apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fitness-pvc
  namespace: chandana-ns
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: "2Gi"
  storageClassName: ""
